---
kind: ConfigMap
apiVersion: v1
metadata:
  name: log-config
data:
  log.properties: |
    # Root logger option
    log4j.rootLogger=DEBUG, stdout, file
    # Redirect log messages to console
    log4j.appender.stdout=org.apache.log4j.ConsoleAppender
    log4j.appender.stdout.Target=System.out
    log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
    log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
    # Redirect log messages to a log file, support file rolling.
    log4j.appender.file=org.apache.log4j.RollingFileAppender
    log4j.appender.file.File=log4j-application.log
    log4j.appender.file.MaxFileSize=5MB
    log4j.appender.file.MaxBackupIndex=10
    log4j.appender.file.layout=org.apache.log4j.PatternLayout
    log4j.appender.file.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: wishlist-deployment
  labels:
    app: wishlist
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wishlist
  template:
    metadata:
      labels:
        app: wishlist
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: log-config
      containers:
      - name: wishlist
        image: karthequian/wishlist:1.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        volumeMounts:
        - name: config-volume
          readOnly: true
          mountPath: "/var/lib/wishlist/"
      - name: catalog
        image: karthequian/wishlist-catalog:1.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
        env:
        - name: PORT
          value: "8081"
        volumeMounts:
        - name: config-volume
          readOnly: true
          mountPath: "/var/lib/wishlist/"
      - name: auth
        image: karthequian/wishlist-auth:1.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8082
        env:
        - name: PORT
          value: "8082"
        volumeMounts:
        - name: config-volume
          readOnly: true
          mountPath: "/var/lib/wishlist/"
---
kind: Service
apiVersion: v1
metadata:
  name: wishlist-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: wishlist
  ports:
  - name: wishlist-port
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: wishlist-catalog-port
    protocol: TCP
    port: 8081
    targetPort: 8081
  - name: wishlist-auth-port
    protocol: TCP
    port: 8082
    targetPort: 8082
