---
# Configmap definition
kind: ConfigMap
apiVersion: v1
metadata:
  name: log-config
data:
  log-level: debug
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: wishlist-deployment
  labels:
    app: wishlist
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wishlist
  template:
    metadata:
      labels:
        app: wishlist
    spec:
      volumes:
        - name: config-volume # Declare config map volume
          configMap:
            name: log-config
      containers:
      - name: wishlist
        image: karthequian/wishlist:1.0
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: LOG_LEVEL
          valueFrom: # Reference the configMap volume name
            configMapKeyRef:
              name: log-config
              key: log-level
      - name: catalog
        image: karthequian/wishlist-catalog:1.0
        ports:
        - containerPort: 8081
        env:
        - name: PORT
          value: "8081"
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: log-config
              key: log-level
      - name: auth
        image: karthequian/wishlist-auth:1.0
        ports:
        - containerPort: 8082
        env:
        - name: PORT
          value: "8082"
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: log-config
              key: log-level
---
kind: Service
apiVersion: v1
metadata:
  name: wishlist-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: wishlist
  ports:
  - name: wishlist-port
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: wishlist-catalog-port
    protocol: TCP
    port: 8081
    targetPort: 8082
  - name: wishlist-auth-port
    protocol: TCP
    port: 8082
    targetPort: 8082


   


