---
# Wishlist app deployment
kind: Deployment
apiVersion: apps/v1
metadata:
  name: wishlist-app-deployment
  labels:
    app: wishlist-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wishlist-app-deployment
  template:
    metadata:
      labels:
        app: wishlist-app-deployment
    spec:
      containers:
      - name: wishlist-app-deployment
        image: karthequian/wishlist:1.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
---
# Wishlist catalog deployment
kind: Deployment
apiVersion: apps/v1
metadata:
  name: wishlist-catalog-deployment
  labels:
    app: wishlist-catalog-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wishlist-catalog-deployment
  template:
    metadata:
      labels:
        app: wishlist-catalog-deployment
    spec:
      containers:
      - name: catalog
        image: karthequian/wishlist-catalog:1.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
        env:
        - name: PORT
          value: "8081"
---
# Wishlist auth deployment
kind: Deployment
apiVersion: apps/v1
metadata:
  name: wishlist-auth-deployment
  labels:
    app: wishlist-auth-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wishlist-auth-deployment
  template:
    metadata:
      labels:
        app: wishlist-auth-deployment
    spec:
      containers:
      - name: auth
        image: karthequian/wishlist-auth:1.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8082
        env:
        - name: PORT
          value: "8082"
---
# Wishlist app service
kind: Service
apiVersion: v1
metadata:
  name: wishlist-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: wishlist-app-deployment
  ports:
  - name: wishlist-port
    protocol: TCP
    port: 8080
    targetPort: 8080
---
# Wishlist catalog service
kind: Service
apiVersion: v1
metadata:
  name: wishlist-catalog-service
spec:
  type: NodePort
  selector:
    app: wishlist-catalog-deployment
  ports:
  - name: wishlist-catalog-port
    protocol: TCP
    port: 8081
    targetPort: 8081
---
# Wishlist auth service
kind: Service
apiVersion: v1
metadata:
  name: wishlist-auth-service
spec:
  type: NodePort
  selector:
    app: wishlist-auth-deployment
  ports:
  - name: wishlist-auth-port
    protocol: TCP
    port: 8082
    targetPort: 8082