apiVersion: v1
kind: Pod
metadata:
  name: myconfigmappod
  namespace: purple
spec:
  containers:
  - image: nginx
    name: myconfigmappod
    env:
    - name: MY_EXAM_ENV
      valueFrom:
        configMapKeyRef:
          name: myconfigmap
          key: exam
