apiVersion: v1
kind: Pod
metadata:
  name: mylivenesspod
  namespace: purple
spec:
  containers:
  - image: nginx
    name: mylivenesspod
    livenessProbe:
      httpGet:
        path: /
        port: 80
      periodSeconds: 5
