Vagrant.configure("2") do |config|
  # Define the box to use for both VMs
  config.vm.box = "generic/ubuntu2204"

  # Configure the provider to use libvirt
  config.vm.provider :libvirt do |libvirt|
    libvirt.uri = "qemu:///system"
  end

  # Define the cp VM
  config.vm.define "cp" do |cp|
    cp.vm.hostname = "cp"

    # Master VM resources
    cp.vm.provider :libvirt do |libvirt|
      libvirt.cpus = 2
      libvirt.memory = 8192
    end
  end

  # Define the worker VM
  config.vm.define "worker1" do |worker|
    worker.vm.hostname = "worker1"

    # Worker VM resources
    worker.vm.provider :libvirt do |libvirt|
      libvirt.cpus = 2
      libvirt.memory = 4096
    end
  end

  # Define the worker VM
  config.vm.define "worker2" do |worker|
    worker.vm.hostname = "worker2"

    # Worker VM resources
    worker.vm.provider :libvirt do |libvirt|
      libvirt.cpus = 2
      libvirt.memory = 4096
    end
  end
end
