apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  namespace: blue
spec:
  storageClassName: manual
  volumeName: mypv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
