Vagrant.configure("2") do |config|
  # Define the box to use for both VMs
  config.vm.box = "generic/ubuntu2204"

  # Configure the provider to use libvirt
  config.vm.provider :libvirt do |libvirt|
    libvirt.uri = "qemu:///system"
  end

  # Define the cp VM
  config.vm.define "cp" do |cp|
    cp.vm.hostname = "cp"
    #cp.vm.network "private_network", type: "dhcp", libvirt__network_name: "default"

    # Master VM resources
    cp.vm.provider :libvirt do |libvirt|
      libvirt.cpus = 2
      libvirt.memory = 8192 # 8 GB RAM
    end
  end

  # Define the worker VM
  config.vm.define "worker" do |worker|
    worker.vm.hostname = "worker"
    #worker.vm.network "private_network", type: "dhcp", libvirt__network_name: "default"

    # Worker VM resources
    worker.vm.provider :libvirt do |libvirt|
      libvirt.cpus = 2
      libvirt.memory = 4096 # 4 GB RAM
    end
  end
end
